### ISSUE TITLE
Add versioning, at least a checkpoint version, then use semver going forward

### ISSUE THREAD

**Issue by mtheoryx** [stingerlabs/ember-graph#79]

**Comment by gordonkristan** [comment]
This was always my goal. The problem was that we were making breaking API changes so rapidly that having a version simply didn't matter. Any semver version number below 1.0.0 is useless since it doesn't provide any kind of API guarantees. I always wanted to stabilize the API and feature set, then draw a hard 1.0.0 line in the sand. But as you'll see from the milestones I've created (and incompleteness), what we were doing didn't exactly agree with that goal.

So short story long, let's agree on a 1.0.0 feature set then do it. :+1:

**Comment by mtheoryx** [comment]
I think we have what I'd consider a pretty stable featureset to cut a 1.0.0 now

**Comment by mtheoryx** [comment]
Closed by #78

**Comment by mtheoryx** [comment]
Closed by #88
