### ISSUE TITLE
Question: Recursive relationships and non-standard api points

### ISSUE THREAD

**Issue by matthewnessworthy** [stingerlabs/ember-graph#83]
Does ember-graph support defining relationship endpoints for the children of the same model types, like a file/folder structure?
Specifically related to loading children from a single endpoint like /node/1/children instead for sideloading or embedding records. This is primarily due to having child records in excess of 2000 elements and numerous sub-sub-sub nodes.

**Comment by gordonkristan** [comment]
Yes, it does. It's not quite as easy as Ember Data out of the box, but it's not too difficult.

First you'll want to get your parent node without specifying the children. So `store.find('node', 1)` should return something like this:

```json
{
	"id": 1,
	"links": {
		"parent": null,
		"children": []
	}
}
```

Next, you'll want to override your adapter's `findQuery` method so you can make the query. Something like this (if you're using the [RESTAdapter](https://github.com/stingerlabs/ember-graph/blob/8a828a8914e3e1c060af2d649256d8af4ffa6d8f/src/adapter/rest.js#L109)):

```js
findQuery(typeKey, query) {
	const url = `/nodes/${query.parent}/children`;

	return this.ajax(url, 'GET').then((payload) => {
		return this.deserialize(payload, { requestType: 'findQuery', recordType: typeKey, query: query });
	});
}
```

The final step is to return the correct payload for the API call above. In this case, you simply return all of the children in a `nodes` array.

```json
{
	"nodes": [
		{
			"id": 50,
			"links": {
				"parent": 1,
				"children": []
			}
		},
		{
			"id": 51,
			"links": {
				"parent": 1,
				"children": []
			}
		}
	]
}
```

Ember Graph will then wire up all of the relationships for you as soon as it pushes the payload into the store.

So really there's just 2 things you need to do:

1. Modify the adapter so that it makes the call to the correct URL (which depends on your server)
2. Ensure that your server is returning data in the correct format for your serializer.

There's also an optional step. You can do something like this to make this situation easier to deal with:

```js
const Node = EmberGraph.Model.extend({
	parent: EmberGraph.hasOne({
		relatedType: 'node',
		inverse: 'children'
	}),

	children: EmberGraph.hasMany({
		relatedType: 'node',
		inverse: 'parent'
	}),

	allChildren: Ember.computed({
		get() {
			const id = this.get('id');

			return this.get('store').find('node', { parent: id });
		}
	})
});
```

Now instead of using `store.find('node', { parent: parent.get('id') })` you can just use `parent.get('allChildren')`.

**Comment by matthewnessworthy** [comment]
Excellent, thanks for the extended write-up! I'll give it a shot.
